import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const markdownStyles = `
prose
prose-lg
max-w-none
mt-10

prose-headings:text-slate-900
prose-headings:font-bold
prose-headings:tracking-tight

prose-h1:text-4xl
prose-h2:text-3xl
prose-h3:text-2xl

prose-p:text-slate-700
prose-p:leading-8

prose-li:text-slate-700
prose-li:leading-8

prose-strong:text-slate-900

prose-code:text-indigo-700
prose-code:font-semibold

prose-pre:bg-slate-900
prose-pre:text-white
prose-pre:rounded-xl
prose-pre:p-5
prose-pre:shadow-md
prose-pre:overflow-x-auto

prose-blockquote:border-indigo-500
prose-blockquote:text-slate-600

prose-hr:my-10

prose-table:w-full
prose-table:border-collapse

prose-th:border
prose-th:border-slate-300
prose-th:bg-slate-100
prose-th:px-4
prose-th:py-3
prose-th:text-left
prose-th:font-semibold

prose-td:border
prose-td:border-slate-300
prose-td:px-4
prose-td:py-3
`;

export default function PrintableNotes({
  subject,
  topic,
  educationLevel,
  content,
  generatedAt,
}) {
  const generatedDate = generatedAt ? new Date(generatedAt) : new Date();

  const generatedDateOnly = generatedDate.toLocaleDateString();

  const generatedDateTime = generatedDate.toLocaleString();
  return (
    <div
      className="relative bg-white text-black mx-auto p-12"
      style={{
        maxWidth: "210mm",
        width: "100%",
        minHeight: "297mm",
      }}
    >
      {/* Header */}
      <header className="mb-10 border-b-2 border-indigo-600 pb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-5xl font-extrabold tracking-tight text-indigo-700">
              ExamAI
            </h1>

            <p className="mt-2 text-lg font-medium text-slate-700">
              AI Generated Study Notes
            </p>

            <p className="mt-1 text-sm text-slate-500">
              Personalized • Structured • Exam Focused
            </p>
            <div className="mt-5 h-1 w-24 rounded-full bg-indigo-600"></div>
          </div>

          <div className="rounded-xl border border-indigo-200 bg-indigo-50 px-5 py-3 text-right">
            <p className="text-xs uppercase tracking-wider text-slate-500">
              Generated
            </p>

            <p className="mt-1 font-semibold text-slate-800">
              {generatedDateOnly}
            </p>
          </div>
        </div>
      </header>

      {/* Information Card */}
      <section className="mb-10 rounded-2xl border border-slate-300 bg-slate-50 p-6 shadow-sm">
        <div className="grid grid-cols-2 gap-8">
          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              📚 Subject
            </p>

            <h2 className="mt-1 text-lg font-bold text-slate-900">
              {subject || "N/A"}
            </h2>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              🎯 Topic
            </p>

            <h2 className="mt-1 text-lg font-bold text-slate-900">
              {topic || "N/A"}
            </h2>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              🎓 Education Level
            </p>

            <h2 className="mt-1 text-lg font-bold text-slate-900">
              {educationLevel || "N/A"}
            </h2>
          </div>

          <div>
            <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">
              🤖 Generated By
            </p>

            <h2 className="mt-1 text-lg font-bold text-indigo-700">ExamAI</h2>
          </div>
        </div>
      </section>

      {/* Notes */}
      <article className={markdownStyles}>
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {content || "No content Generated."}
        </ReactMarkdown>
      </article>

      {/* Footer */}
      <footer className="mt-16 border-t border-slate-300 pt-6">
        <div className="flex items-center justify-between text-sm text-slate-500">
          <div>
            <p className="font-medium text-slate-700">Generated by ExamAI</p>
            <p>AI-Powered Study Assistant</p>
          </div>

          <div className="text-right">
            <p>Generated on</p>
            <p className="font-medium text-slate-700">{generatedDateTime}</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
